name: Validate typescript

on: [pull_request]

jobs:
  validate_typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run validate:ts
